### ISSUE TITLE
Next chapter button missing on chapter 5 page

### ISSUE THREAD

**Issue by DritchJaul** [pascalstockert/yolol#5]
On [Chapter 5](https://pascalstockert.github.io/yolol/chapter5) the "Next chapter" button is missing.
![image](https://user-images.githubusercontent.com/5302873/73616315-7c111180-45d7-11ea-9dc2-64597a331526.png)

**Comment by pascalstockert** [comment]
Fixed! Thanks for letting me know, appreciate it! ❤️
