### ISSUE TITLE
Feature request: string pre decrement

### ISSUE THREAD

**Issue by Matrix89** [pascalstockert/yolol#69]
Doing a string pre decrementation should remove the first character not the last one.
Expected behaviour:
```
input = "Hello World!"
--input -- input should be equal to "ello World!"
```

**Comment by Azurethi** [comment]
May seem logical, but [per the description on the starbase wiki](https://wiki.starbasegame.com/index.php/YOLOL#Operators_and_commands), both pre & post decrement do the same thing to strings.

A--
> **Removes the last character of the string.** Results in runtime error when trying to remove "". Evaluates to the original value.

--A
> **Removes the last character of the string.** Results in runtime error when trying to remove "". Evaluates to the modified value.


p.s: me replying since this is a yazur related thing :)
